### ISSUE TITLE
trouble downloading

### ISSUE THREAD

**Issue by FB4Studios** [chaudharirohit2810/SpotIT#2]
i try to download the app it loads and crashes when i open it please fix this

**Comment by chaudharirohit2810** [comment]
Hi and thank you for adding the issue!
Can you add some more details like android version, phone model and screenshots supporting the issue?

**Comment by FB4Studios** [comment]
hi thanks for getting back my android verison is 10 and model Samsung galaxy a70 it kinda works now just crashed sometimes and i don't have scareenshots

**Comment by chaudharirohit2810** [comment]
Ok, Thanks!
I will close the issue for now, if you face the same issue again feel free to reopen it.
