### ISSUE TITLE
App doesn't work when ads kick in

### ISSUE THREAD

**Issue by sotracez** [chaudharirohit2810/SpotIT#3]
I am using the app on Xiaomi Redmi Note 7 with Android 10, I whitelist the app in Apps Battery Saver as well as provided the app with notification access, but the app refused to work on my phone, btw F-Droid is not displaying the latest version(0.1.1) at the time I am writing this. (btw I love the design of the app)

**Comment by chaudharirohit2810** [comment]
Thanks 😄 
There is some problem with Xiaomi devices as it kills the app's service in background and I will try to fix it in my next version.
