### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sree874** [chaudharirohit2810/SpotIT#4]
It still plays Spotify ads

**Comment by chaudharirohit2810** [comment]
Can you please mention your smartphone model?

**Comment by sree874** [comment]
Realme c12

**Comment by chaudharirohit2810** [comment]
Yeah, this is the issue with Realme, Xiaomi, Oppo, and Vivo smartphones, they do not allow notification access in the background. You can check #3 . I will try to fix it in the next version.

**Comment by sree874** [comment]
Realme c12
