### ISSUE TITLE
Visual notification while muting ads

### ISSUE THREAD

**Issue by shuvashish76** [chaudharirohit2810/SpotIT#6]
Just like https://github.com/abertschi/ad-free show a visual notification while muting ads.
![Screenshot](https://user-images.githubusercontent.com/48226312/104154258-7c7e7300-540a-11eb-9329-dc2c0b95ad37.png)

**Comment by chaudharirohit2810** [comment]
Thanks for the suggestion 😄 

I think that will be bothering for some but I will add it as optional feature in the next version.
